githubRepoOwner: Pocket
githubRepoName: Android
githubBranch: main
prTemplatePath: .github/PULL_REQUEST_TEMPLATE.md
prTemplateInsertStart: "<!-- If you opened this PR with `git spr` feel free to copy anything it generated here into the PR body."
prTemplateInsertEnd: "spr -->"
