projects:
  prod:
    schema: sync-pocket/src/main/graphql/pocket-client-api@current.graphqls
    include:
    - sync-pocket/src/main/graphql/**
    - figment.graphql
    extensions:
      endpoints:
        Pocket Graph – Production:
          url: https://client-api.getpocket.com
          headers:
            user-agent: JS GraphQL
          introspect: false
  test:
    schema: sync-pocket-android/src/test/graphql/test.graphqls
    include:
    - sync-pocket-android/src/test/graphql/**
    - figment.graphql
  examples:
    schema: sync-gen/examples/graphql/examples.graphqls
    include:
    - sync-gen/examples/graphql/**
    - figment.graphql
