name: On Git reference created

on: create

jobs:
  on-release-branch-created:
    if: startsWith(github.ref_name, 'release-')
    name: On release branch created
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Open release PR
      run: scripts/open-release-pr.sh "${{ github.ref_name }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
