name: On Git reference created

on:
  create

jobs:
  on-release-branch-created:
    if: startsWith(github.ref_name, 'release-')
    name: On release branch created
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
    - name: Open release PR
      run: scripts/open-release-pr.sh "${{ github.ref_name }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
