name: PR checks

on:
  pull_request:
  merge_group:

# Cancel in-progress/pending PR checks if a new commit is pushed to the branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  android-lint:
    name: Android Lint
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Set up environment
      uses: ./.github/actions/setup-environment
      with:
        gradle: true
    - name: Decrypt secrets
      env:
        GPG_KEY: ${{ secrets.gpg_key }}
      run: secrets/decrypt.sh
    - name: Run Android Lint
      run: scripts/run-android-lint.sh

  licenses:
    name: Validate licenses
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Set up environment
      uses: ./.github/actions/setup-environment
      with:
        gradle: true
    - name: Decrypt secrets
      env:
        GPG_KEY: ${{ secrets.gpg_key }}
      run: secrets/decrypt.sh
    - name: Validate licenses
      run: scripts/run-license-checks.sh
